apiVersion: v1              # Service is a core resource
kind: Service
metadata:
  name: urban-service
spec:
  selector:
    app: urban            # find ALL pods with label app=urban
  ports:
    - protocol: TCP
      port: 80              # port the service listens on (inside cluster)
      targetPort: 3000      # port your app listens on inside the container
  type: ClusterIP          # only accessible inside the cluster