import { useState } from 'react'
import { Bot, Lightbulb, Sparkles, Target } from 'lucide-react'
import Badge from '../common/Badge.jsx'
import { formatRelativeTime } from '../../utils/formatDate.js'

/**
 * AI insight card.
 *
 * Appears on the report detail, the dashboard and the analytics page. The
 * payload (`report.aiInsight`, `analytics.aiInsights`) is generated by the risk
 * engine - this component only presents it, and always shows the confidence so
 * a human can weigh the recommendation.
 */
export default function AiInsightCard({ insight, className = '', compact = false }) {
  const [expanded, setExpanded] = useState(false)

  if (!insight) return null

  const confidence = Math.round((insight.confidence ?? 0) * 100)

  return (
    <article className={`card overflow-hidden ${className}`}>
      <header className="flex items-center gap-2.5 border-b border-violet-100 bg-violet-50/60 px-5 py-3.5">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-100 text-violet-600">
          <Bot size={16} aria-hidden="true" />
        </span>
        <div className="min-w-0 flex-1">
          <p className="text-[13px] font-bold text-violet-900">AI Risk Insight</p>
          <p className="text-[10px] text-violet-600">
            {insight.generatedBy ?? 'UbranShieldAI Risk Engine'}
            {insight.createdAt ? ` · ${formatRelativeTime(insight.createdAt)}` : ''}
          </p>
        </div>
        {insight.priority ? <Badge tone={insight.priority} size="sm">{insight.priority} priority</Badge> : null}
      </header>

      <div className="space-y-4 p-5">
        <div>
          <p className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-muted">
            <Sparkles size={11} aria-hidden="true" />
            Assessment
          </p>
          <p className="mt-1.5 text-sm font-semibold text-ink">{insight.title}</p>
          <p className={`mt-1.5 text-[13px] leading-relaxed text-body ${compact && !expanded ? 'line-clamp-3' : ''}`}>
            {insight.description}
          </p>
        </div>

        {insight.recommendation ? (
          <div className="rounded-xl border border-brand-100 bg-brand-50/60 p-4">
            <p className="flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide text-brand-700">
              <Lightbulb size={11} aria-hidden="true" />
              Recommended action
            </p>
            <p className="mt-1.5 text-[13px] leading-relaxed text-ink">{insight.recommendation}</p>
          </div>
        ) : null}

        <div className="flex flex-wrap items-center gap-4">
          <div className="min-w-[160px] flex-1">
            <div className="flex items-baseline justify-between text-[11px]">
              <span className="font-medium text-body">Model confidence</span>
              <span className="font-bold text-ink">{confidence}%</span>
            </div>
            <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-slate-100">
              <div
                className="h-full rounded-full bg-violet-500 transition-[width] duration-500"
                style={{ width: `${confidence}%` }}
              />
            </div>
          </div>

          {compact && insight.description?.length > 160 ? (
            <button
              type="button"
              onClick={() => setExpanded((value) => !value)}
              className="text-[11px] font-semibold text-violet-600 hover:underline"
            >
              {expanded ? 'Show less' : 'Read more'}
            </button>
          ) : null}
        </div>
      </div>
    </article>
  )
}

/** Compact list variant for the AI assistant rail. */
export function AiInsightList({ insights = [], emptyMessage = 'No AI insights generated yet.' }) {
  if (!insights.length) {
    return (
      <p className="rounded-xl border border-dashed border-line px-4 py-6 text-center text-xs text-muted">{emptyMessage}</p>
    )
  }

  return (
    <ul className="space-y-3">
      {insights.map((insight, index) => (
        <li key={insight.id ?? insight.title ?? index} className="card p-4">
          <p className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-violet-600">
            <Target size={11} aria-hidden="true" />
            {insight.ward ?? 'City wide'} · {Math.round((insight.confidence ?? 0) * 100)}% confidence
          </p>
          <p className="mt-1.5 text-[13px] font-semibold text-ink">{insight.title}</p>
          <p className="mt-1 text-[12px] leading-relaxed text-body">{insight.description}</p>
          {insight.action ? <p className="mt-2 text-[12px] font-medium text-brand-700">→ {insight.action}</p> : null}
        </li>
      ))}
    </ul>
  )
}
